services:

  spring-app:
    image: application:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/social_network
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres-db

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

