version: '3'

services:
  app:
    image: 'web-application:latest'
    build: backend
    restart: on-failure
    container_name: app
    depends_on:
      - db
    ports:
      - '8081:8082'

    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/userDb
      - SPRING_DATASOURCE_USERNAME=gleb
      - SPRING_DATASOURCE_PASSWORD=gleb123

  db:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=gleb
      - POSTGRES_PASSWORD=gleb123
    ports:
      - '5433:5432'
